
print("1. Education helps us gain knowledge.")
print("2. It teaches us discipline and manners.")
print("3. Education improves our thinking ability.")
print("4. It helps us get good jobs in the future.")
print("5. Educated people can make better decisions.")
print("6. Schools and colleges provide education.")
print("7. Education reduces poverty and unemployment.")
print("8. It helps in the development of society.")
print("9. Everyone should get equal education opportunities.")
print("10. Education is the key to success.\n\n")


print(" The internet is used all over the world.")
print(" It helps us find information quickly.")
print(" Students use it for online learning.")
print(" People can communicate through emails and chats.")
print(" It is useful for online shopping and banking.")
print(" The internet provides entertainment like videos and games.")
print(" Businesses use it for marketing and communication.")
print(" Social media works through the internet.")
print(" It saves time and effort in many tasks.")
print(" The internet has become an important part of life.\n\n")


print("My favorite teacher is very kind and helpful.")
print("She teaches us with great patience.")
print("Her way of teaching is very interesting.")
print("She always motivates students to study well.")
print("She explains difficult topics in a simple way.")
print("She encourages us to ask questions.")
print("She treats every student equally.")
print("She also teaches us good values.")
print("I respect her very much.")
print("She is an inspiration for me.\n\n")


print("The environment is very important for life.")
print("Trees give us oxygen and fresh air.")
print("Pollution harms the environment badly.")
print("We should plant more trees.")
print("Plastic waste should be reduced.")
print("Water and electricity should not be wasted.")
print("Recycling helps protect nature.")
print("Clean surroundings keep us healthy.")
print("Everyone should take care of the environment.")
print("Saving the environment means saving our future.\n\n")


print("My best friend is very honest and caring.")
print("We study and play together.")
print("He always helps me in difficult times.")
print("We share our secrets with each other.")
print("He is good at sports and studies.")
print("We enjoy spending time together.")
print("He respects teachers and elders.")
print("He always encourages me to do better.")
print("Our friendship is very strong.")
print("I am lucky to have such a good friend.")